Create the secret resource
1. Remove required validation for rootpassword
```
$ kubectl apply -f ./config/samples/mariak8g_v1alpha1_mariadb.yaml
error: error validating "./config/samples/mariak8g_v1alpha1_mariadb.yaml": error validating data: ValidationError(MariaDB.spec): missing required field "rootpwd" in org.mariadb.mariak8g.v1alpha1.MariaDB.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
----------
Reason:
----------
One can use secrets created by operator (this patch), where we can change the password of the secrets (in base64: `echo -n 'secret'|base64`)
2. Secrets in the patch
a) default password: `mysecret`

- Testing the secrets:
```
$ kubectl apply -f ./config/samples/mariak8g_v1alpha1_mariadb.yaml
mariadb.mariak8g.mariadb.org/mariadb-sample created

$ kubectl get secrets
NAME                    TYPE                                  DATA   AGE
default-token-blb5w     kubernetes.io/service-account-token   3      129d
mariadb-sample-secret   Opaque                                1      73s
```

- Proof that key is used from secret
```
$ kubectl describe pods mariadb-sample-server-deployment-5b5f67b795-qckp5
    Environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD:  0
      MARIADB_ROOT_PASSWORD:              <set to the key 'mariadb-root-password' in secret 'mariadb-sample-secret'>  Optional: false

```
- Reconciliation is working:
```
2022-03-06T17:43:09.421-0800    INFO    controller.mariadb      Starting EventSource    {"reconciler group": "mariak8g.mariadb.org", "reconciler kind": "MariaDB", "source": "kind source: /, Kind="}
2022-03-06T17:43:09.421-0800    INFO    controller.mariadb      Starting Controller     {"reconciler group": "mariak8g.mariadb.org", "reconciler kind": "MariaDB"}
2022-03-06T17:43:09.525-0800    INFO    controller.mariadb      Starting workers        {"reconciler group": "mariak8g.mariadb.org", "reconciler kind": "MariaDB", "worker count": 1}
2022-03-06T17:43:34.985-0800    INFO    controllers.MariaDB1    Reconciling MariaDB kind        {"MariaDB: ": "default/mariadb-sample", "mariadb": ""}
2022-03-06T17:43:34.985-0800    INFO    controllers.MariaDB1    No root password set. Create the secret!        {"MariaDB: ": "default/mariadb-sample"}
2022-03-06T17:43:34.985-0800    INFO    controllers.MariaDB1    Secret created !        {"MariaDB: ": "default/mariadb-sample", "mariadb-root-password: ": {"kind":"Secret","apiVersion":"v1","metadata":{"name":"mariadb-sample-secret","namespace":"default","creationTimestamp":null,"ownerReferences":[{"apiVersion":"mariak8g.mariadb.org/v1alpha1","kind":"MariaDB","name":"mariadb-sample","uid":"5c380104-4917-4a37-a044-9452b4ef7b94","controller":true,"blockOwnerDeletion":true}]},"data":{"mariadb-root-password":"bXlzZWNyZXQ="},"type":"Opaque"}}
2022-03-06T17:43:34.990-0800    INFO    controllers.MariaDB1    Checking the deployment status  {"MariaDB: ": "default/mariadb-sample", "mariadb-deployment-status": {}}
2022-03-06T17:43:35.041-0800    INFO    controllers.MariaDB1    Reconciled MariaDB kind {"MariaDB: ": "default/mariadb-sample", "mariadb": "mariadb-sample", "status": {"desiredReplicas":0,"lastMessage":"","dbState":"RUNNING","showState":"RUNNING","secretSet":1}}
2022-03-06T17:43:35.041-0800    INFO    controllers.MariaDB1    Reconciling MariaDB kind        {"MariaDB: ": "default/mariadb-sample", "mariadb": ""}
2022-03-06T17:43:35.041-0800    INFO    controllers.MariaDB1    Root password set, skip secret creation!        {"MariaDB: ": "default/mariadb-sample", "mariadb-root-password: ": ""}
2022-03-06T17:43:35.041-0800    INFO    controllers.MariaDB1    Checking the deployment status  {"MariaDB: ": "default/mariadb-sample", "mariadb-deployment-status": {}}
2022-03-06T17:43:35.095-0800    INFO    controllers.MariaDB1    Reconciled MariaDB kind {"MariaDB: ": "default/mariadb-sample", "mariadb": "mariadb-sample", "status": {"desiredReplicas":0,"lastMessage":"","dbState":"RUNNING","showState":"RUNNING","secretSet":1}}
2022-03-06T17:43:35.095-0800    INFO    controllers.MariaDB1    Reconciling MariaDB kind        {"MariaDB: ": "default/mariadb-sample", "mariadb": ""}
2022-03-06T17:43:35.095-0800    INFO    controllers.MariaDB1    Root password set, skip secret creation!        {"MariaDB: ": "default/mariadb-sample", "mariadb-root-password: ": ""}
2022-03-06T17:43:35.096-0800    INFO    controllers.MariaDB1    Checking the deployment status  {"MariaDB: ": "default/mariadb-sample", "mariadb-deployment-status": {}}
2022-03-06T17:43:35.120-0800    INFO    controllers.MariaDB1    Reconciled MariaDB kind {"MariaDB: ": "default/mariadb-sample", "mariadb": "mariadb-sample", "status": {"desiredReplicas":0,"lastMessage":"","dbState":"RUNNING","showState":"RUNNING","secretSet":1}}
2022-03-06T17:43:50.168-0800    INFO    controllers.MariaDB1    Reconciling MariaDB kind        {"MariaDB: ": "default/mariadb-sample", "mariadb": ""}
```
- Blueprint of a secret:
```
2022-03-06T16:36:45.443-0800    INFO    controllers.MariaDB1    Secret created !
{"MariaDB: ": "default/mariadb-sample",
"mariadb-root-password: ":
{"kind":"Secret",
  "apiVersion":"apps/v1",
  "metadata":{"name":"mariadb-sample-secret","namespace":"default","creationTimestamp":null,"ownerReferences":[{"apiVersion":"mariak8g.mariadb.org/v1alpha1","kind":"MariaDB","name":"mariadb-sample","uid":"5110893f-f6f9-47ac-8207-6ffad2e6dab0","controller":true,"blockOwnerDeletion":true}]},
  "data":{"mariadb-root-password":"bXlzZWNyZXQ="},
  "type":"Opaque"}}
```

- Testing the root connection (works)
```
$ kubectl exec svc/mariadb-sample-server-service -- mariadb -uroot -pmysecret -e "select version()"
version()
10.6.8-MariaDB-1:10.6.8+maria~focal
```

b) Edit the secret - note this work after minikube is restarted / @todo
```
$ echo -n "newsecret"|base64
bmV3c2VjcmV0

$ kubectl edit secret mariadb-sample-secret

$ echo -n "bmV3c2VjcmV0"|base64 -d

$ kubectl exec svc/mariadb-sample-server-service -- mariadb -uroot -pnewsecret -e "select version()"
version()
10.6.8-MariaDB-1:10.6.8+maria~focal

```

@todo - check the API (PatchStatus?) how to properly monitor for the keys in secret and do valid reconciliation

Future work - Statefulset application